### PR TITLE
allow the user to configure the riemann host and port using environment variables

### PR DESCRIPTION
**Pull request by SamRoberts**
Hi Peter,

I'd like to bump up the version with this PR, but I'm not sure how that would work with the version scheme here that seems to track docker. `0.7.1`? `0.7.0.1`? Please let me know,

Thanks,
Sam

### CODE REVIEW

**Comment by pdericson** [comment]
This looks great @SamRoberts but can you please start with a copy of 0.7.0 -> 0.7.1 and then apply your change as a separate commit?

**Comment by SamRoberts** [comment]
@pdericson done

**Comment by pdericson** [comment]
Thanks @SamRoberts

**Comment by SamRoberts** [comment]
You are welcome :)

**Pull request merged**
